import React, { useState } from "react";
import ListNavbar from "./ListNavbar";
import {
  MainContainerListCard,
  MainContainer,
  ImageContainer,
  AddressContainer,
  DetailsContainer,
  ImageAndDetailsContainer,
  RentDataDiv,
  RowDetailsContainer
} from "./Skins";
import BGImage1 from "../assets/BGImage1.png";
import Carousel from "./Carousel";

export default function ProductListPage() {
  const [GoDown, setGoDown] = useState<boolean>(false);

  const HandleGODownFunc = (value: boolean) => {
    setGoDown(value);
  };

  return (
    <div>
      <ListNavbar HandleGODownFunc={HandleGODownFunc} />
      <MainContainer GoDown={GoDown}>
        <MainContainerListCard>
          <AddressContainer> this is address bar </AddressContainer>
          <ImageAndDetailsContainer>
            <Carousel/>
            <DetailsContainer>
            <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
              <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
              <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
            </DetailsContainer>
          </ImageAndDetailsContainer>
        </MainContainerListCard>

        <MainContainerListCard>
          <AddressContainer> this is address bar </AddressContainer>
          <ImageAndDetailsContainer>
          <Carousel/>
            <DetailsContainer>
            <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
              <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
              <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
            </DetailsContainer>
          </ImageAndDetailsContainer>
        </MainContainerListCard>

        <MainContainerListCard>
          <AddressContainer> this is address bar </AddressContainer>
          <ImageAndDetailsContainer>
          <Carousel/>
            <DetailsContainer>
            <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
              <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
              <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
            </DetailsContainer>
          </ImageAndDetailsContainer>
        </MainContainerListCard>

        <MainContainerListCard>
          <AddressContainer> this is address bar </AddressContainer>
          <ImageAndDetailsContainer>
          <Carousel/>
            <DetailsContainer>
            <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
              <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
              <RowDetailsContainer>
              <RentDataDiv>
                <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
              <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              <RentDataDiv>
              <div>rent</div>
                <div>rent</div>
              </RentDataDiv>
              </RowDetailsContainer>
            </DetailsContainer>
          </ImageAndDetailsContainer>
        </MainContainerListCard>
      </MainContainer>
    </div>
  );
}
